name: "store_srv"
mode: "dev"
ip: "127.0.0.1"
rpcPort: 8382
httpPort: 8092
version: "v0.0.1"
start_time: "2023-08-27"
machine_id: 2

log:
  level: "debug"
  filename: "store_srv.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "livesrv"
  max_open_conns: 100
  max_idle_conns: 10

consul:
  address: "127.0.0.1:8500"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100